name: Build and Release Go Project

on:
  push:
    tags:
      - "v*.*.*" # This triggers the workflow on version tags like v1.0.0
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22.2" # Specify the Go version you are using

      - name: Set up Make
        run: sudo apt-get install -y make

      - name: Build with Makefile
        run: make all

      - name: Archive Linux build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hecato-linux
          path: hecato

      - name: Archive Windows build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hecato-windows
          path: hecato.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux build artifacts
        uses: actions/download-artifact@v2
        with:
          name: hecato-linux

      - name: Download Windows build artifacts
        uses: actions/download-artifact@v2
        with:
          name: hecato-windows

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Linux Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./hecato
          asset_name: hecato-linux
          asset_content_type: application/octet-stream

      - name: Upload Windows Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./hecato.exe
          asset_name: hecato-windows.exe
          asset_content_type: application/octet-stream
